const ENHANCED_TRAINING_DATA = {
  "high_stress_keywords": [
    "im",
    "and",
    "cant",
    "so",
    "to",
    "i",
    "dont",
    "know",
    "everything",
    "about",
    "feeling",
    "having",
    "what",
    "depressed",
    "stop",
    "worrying",
    "extremely",
    "hopeless,",
    "go",
    "anxious",
    "on",
    "panic",
    "attacks",
    "breathe",
    "properly",
    "angry",
    "frustrated",
    "how",
    "with",
    "in"
  ],
  "medium_stress_keywords": [
    "i",
    "feel",
    "and",
    "to",
    "the",
    "a",
    "feeling",
    "that",
    "of",
    "my",
    "in",
    "it",
    "like",
    "so",
    "im",
    "for",
    "me",
    "was",
    "have",
    "but",
    "is",
    "this",
    "am",
    "with",
    "not",
    "about",
    "be",
    "as",
    "on",
    "you"
  ],
  "low_stress_keywords": [
    "im",
    "feeling",
    "and",
    "content",
    "in",
    "day",
    "mood",
    "a",
    "with",
    "the",
    "about",
    "my",
    "today",
    "happy",
    "quite",
    "enjoying",
    "relaxed",
    "how",
    "things",
    "are",
    "going",
    "peaceful",
    "calm",
    "good",
    "ease",
    "at",
    "forward",
    "positive",
    "to",
    "grateful"
  ],
  "training_samples": {
    "high": 20,
    "medium": 20020,
    "low": 20
  },
  "dataset_info": {
    "emotion_samples": 20000,
    "local_samples": 20060,
    "total_samples": 20060
  }
};